### ISSUE TITLE
Wind Data

### ISSUE THREAD

**Issue by GWCTas** [LMACRC/weather#1]
The Gust speed is often reporting lower than the wind speed. Check that the data source is correct.

**Comment by stuartcarnie** [comment]
Fixed now, as it was using the AVG function instead of MAX to determine the 10-minute wind-gust statistic.

**Comment by GWCTas** [comment]
The wind is still reporting higher than gusts this evening?

**Comment by GWCTas** [comment]
![Uploading Screen Shot 2021-07-11 at 5.50.15 pm.png…]()

**Comment by stuartcarnie** [comment]
Wind average was over a 24 hour window, wind gust was last 10 minutes. Moved all statistics to 10-minute windows, which is the default for other weather station software.

We can make that configurable in the future if we want to tweak it.
