### ISSUE TITLE
Temperature data

### ISSUE THREAD

**Issue by GWCTas** [LMACRC/weather#2]
Is there a dataset for "Feels Like" i.e. there is a field "Apparent Temperature" but that is reporting the same as actual temperature?

**Comment by stuartcarnie** [comment]
My current outside temperature is `3.4°C`, but my Apparent Temperature is `-0.1°C`:

```
Timestamp           : Saturday, 10-Jul-21 08:40:14 AEST
OutdoorTemperature  : 3.4 °C
OutdoorHumidity     : 87
DewPoint            : 1.4 °C
WindSpeedAvg        : 7.0 km/h
WindSpeedLast       : 9.0 km/h
WindBearing         : 77.0°
SolarRadiation      : 35.5 w/m²
TenMinWindBearingAvg: 68.0°
ApparentTemp        : -0.1 °C
TempFeelsLike       : -0.1 °C
```

`weather` uses the Australian meteorology [Apparent Temperature formula](http://www.bom.gov.au/info/thermal_stress/#atapproximation), which uses current temperature, wind speed and relative humidity:

https://github.com/LMACRC/weather/blob/49a33107862c60353c5ee7528600556cc91a81ca/pkg/weather/meteorology/apparent_temp.go#L9-L16

"Feels Like" is another variation of "Apparent Temperature", used by US meteorology, so we just set it to the same value, as Australian meteorology uses the Apparent Temperature function.

**Comment by GWCTas** [comment]
The Apparent is showing the same as actual Temp. Is that correct?

**Comment by stuartcarnie** [comment]
I see it is showing as the same in this shot, which suggests the weather plugin has a bug or is using one of the other fields:

<img width="333" alt="CleanShot 2021-07-11 at 08 58 51@2x" src="https://user-images.githubusercontent.com/52852/125178241-40479600-e226-11eb-9625-1f9588769267.png">

The realtime.txt specifies the current outdoor temperature and apparent temperature as 4.4 and 2.3 respectively, as bolded below:

11/07/21 08:56:02 **4.4** 86 2.3 6.0 2.6 77 0.0 0.0 1024.8 ENE 3 km/h C hPa mm 53.9 +0.6 17.8 29.7 0.0 22.0 46 2.3 +1.4 4.6 08:56 1.6 07:56 11.1 06:54 14.8 07:01 1024.9 07:23 1023.7 03:47 1.8.2 1 5.5 4.4 4.4 0 0.0 42.5 81 0.0 0 1 0 E 0 m **2.3** 0.0 0 0 2.3

There are two others, Humidex and Heat Index, both of which are currently 4.4 and are using two different formula, but currently match the actual temp.
